# Generated by Django 5.1.5 on 2025-01-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('table_number', models.IntegerField()),
                ('items', models.JSONField()),
                ('status', models.CharField(choices=[('Pending', 'В ожидании'), ('Ready', 'Готово'), ('Paid', 'Оплачено')], default='Pending', max_length=10)),
            ],
        ),
    ]
